name: Create release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
env:
  GPG_SEC: ${{ secrets.PGP_SEC }}
  GPG_PASSWORD: ${{ secrets.PGP_PASSWORD }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # release workflow should have access to all tags
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
      - name: gradle release from tag
        uses: gradle/gradle-build-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          arguments: |
            publishToSonatype
            closeSonatypeStagingRepository
            :save-adapter:shadowJar
            -PsonatypeUsername=${{ secrets.SONATYPE_USER }}
            -PsonatypePassword=${{ secrets.SONATYPE_PASSWORD }}
      - name: gradle snapshot from branch
        uses: gradle/gradle-build-action@v2
        # if workflow is triggered after push to a branch, deploy snapshot
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        with:
          arguments: |
            publishToSonatype
            -PsonatypeUsername=${{ secrets.SONATYPE_USER }}
            -PsonatypePassword=${{ secrets.SONATYPE_PASSWORD }}

      - name: Create Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: save-adapter/build/libs/runner-*-all.jar
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true