name: Create release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
env:
  GPG_SEC: ${{ secrets.PGP_SEC }}
  GPG_PASSWORD: ${{ secrets.PGP_PASSWORD }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # release workflow should have access to all tags
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
      - name: gradle release from tag
        uses: gradle/gradle-build-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          arguments: |
            publishToSonatype
            closeSonatypeStagingRepository
            -PsonatypeUsername=${{ secrets.SONATYPE_USER }}
            -PsonatypePassword=${{ secrets.SONATYPE_PASSWORD }}
      - name: gradle snapshot from branch
        uses: gradle/gradle-build-action@v2
        # if workflow is triggered after push to a branch, deploy snapshot
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        with:
          arguments: |
            publishToSonatype
            -PsonatypeUsername=${{ secrets.SONATYPE_USER }}
            -PsonatypePassword=${{ secrets.SONATYPE_PASSWORD }}